export const MODIFICA_EMAIL = "MODIFICA_EMAIL";
export const MODIFICA_SENHA = "MODIFICA_SENHA";
export const MODIFICA_NOME = "MODIFICA_NOME";
export const CADASTRO_USUARIO_SUCESSO = "CADASTRO_USUARIO_SUCESSO";
export const CADASTRO_USUARIO_ERRO = "CADASTRO_USUARIO_ERRO";
export const LOGIN_USUARIO_SUCESSO = "LOGIN_USUARIO_SUCESSO";
export const LOGIN_USUARIO_ERRO = "LOGIN_USUARIO_ERRO";
export const LOADING = "LOADING";